[package]
edition = "2021"
name = "reuron"
version = "0.1.0"
resolver = "2"

[dependencies]
wasm-bindgen = "^0.2.79"
csv = "^1.1.6"
bevy = "0.10.0"
bevy_mod_picking = { git = "https://github.com/Fincap/bevy_mod_picking", branch = "migrate-bevy-0.10.0" }
bevy_egui = "^0.20"
crossbeam = "^0.8"
ehttp = "^0.2.0"
wgpu = { version = "^0.15", features=["webgl"]}
serde = { version = "1.0.158", features=["serde_derive"]}
serde_json = "1.0.94"
uuid = {version = "1.3.0", features =["wasm-bindgen", "v3","v4","serde", "js"]}

[[bin]]
name = "bevy"
path = "src/bin/bevy.rs"
